apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "tezos.fullname" . }}
  labels:
{{ include "tezos.labels" . | indent 4 }}
spec:
  serviceName: "{{ .Release.Name }}-service"
  replicas: {{ .Values.replicaCount }} # by default is 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "tezos.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "tezos.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
      annotations:
        checksum/configmap.yaml: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        checksum/secret.yaml: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
    spec:
      {{- with .Values.securityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        envFrom:
        - secretRef:
            name: "{{ .Release.Name }}-env"
{{/*        command:*/}}
{{/*          - sh*/}}
{{/*          - -c*/}}
{{/*          - "sleep 999999999"*/}}
        args:
          - tezos-node
          - --net-addr=:{{ .Values.service.p2pPort }}
          - --network={{ .Values.tezos.network }}
          - --history-mode={{ .Values.tezos.history_mode }}
        workingDir: "/home/tezos"
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
        ports:
        - containerPort: {{ .Values.service.rpcPort }}
          name: "{{ .Values.service.rpcPortName }}"
          protocol: "TCP"
        - containerPort: {{ .Values.service.p2pPort }}
          name: "{{ .Values.service.p2pPortName }}"
          protocol: "TCP"
        volumeMounts:
        - name: tezos-pvc
          mountPath: {{ .Values.tezos.base_path }}
        - name: scripts
          mountPath: /scripts
        livenessProbe:
          exec:
            command:
              - /bin/sh
              - /scripts/check_node_health.sh
              - "{{ .Values.tezos.base_path }}"
              - "{{ .Values.tezos.maxHealthyAge }}"
              - last_synced_block.txt
          initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
          timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds }}
          successThreshold: {{ .Values.livenessProbe.successThreshold }}
          failureThreshold: {{ .Values.livenessProbe.failureThreshold }}
      initContainers:
      {{- if .Values.tezos_upgrade_storage }}
      - name: tezos-upgrade-storage
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        envFrom:
        - secretRef:
            name: "{{ .Release.Name }}-env"
        args: ['tezos-upgrade-storage']
        volumeMounts:
          - name: tezos-pvc
            mountPath: {{ .Values.tezos.base_path }}
      {{- end }}
      volumes:
      - name: scripts
        configMap:
          name: "{{ .Release.Name }}-scripts"
  volumeClaimTemplates:
  - metadata:
      name: tezos-pvc
    spec:
      accessModes:
        - {{.Values.persistence.accessMode }}
      {{- if .Values.persistence.storageClass }}
      {{- if (eq "-" .Values.persistence.storageClass) }}
      storageClassName: ""
      {{- else }}
      storageClassName: "{{ .Values.persistence.storageClass }}"
      {{- end }}
      {{- end }}
      resources:
        requests:
          storage: {{ .Values.persistence.size }}
      volumeMode: Filesystem
