apiVersion: v1
appVersion: 0.18.0
description: Bitcoin is an innovative payment network and a new kind of money.
engine: gotpl
home: https://bitcoin.org/
icon: https://bitcoin.org/img/icons/logotop.png
keywords:
- bitcoind
- cryptocurrency
- blockchain
maintainers:
- email: daniel@arilot.com
  name: daniel-yavorovich
- email: shiyanval@gmail.com
  name: govale
name: bitcoind
sources:
- https://github.com/kubernetes/charts
- https://github.com/kuberstack/bitcoind
- https://github.com/kylemanna/docker-bitcoind
version: 0.3.30
